name: Sync GitHub Issues/PRs to Jira

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, reopened, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Send issue/PR to Jira
        run: |
          curl --request POST \
            --url "https://tmfb1207.atlassian.net/rest/api/3/issue" \
            --user "tmfb1207@gmail.com:$JIRA_API_TOKEN" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                "project": { "key": "SCRUM" },
                "summary": "${{ github.event.issue.title || github.event.pull_request.title }}",
                "description": "${{ github.event.issue.body || github.event.pull_request.body }}",
                "issuetype": { "name": "Task" }
              }
            }'
