name: Sync GitHub Issues/PRs to Jira

on: # 2
  issues: 
    types: [opened] 
    
jobs: # 3
  create-issue:  # 4
    name: Create Jira issue # 5
    runs-on: ubuntu-latest # 6
    steps: # 7
    - name: Create Issue 
      uses: atlassian/tmfb1207@v3
      with:
        project: SCRUM  # 10 - 프로젝트 key
        issuetype: Task # 11 - 이슈 타입
        summary: '${{ github.event.issue.title }}'
        description: '${{ github.event.issue.html_url }}'
